name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_config: [secure.conf, insecure.conf]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start services
      env:
        NGINX_CONFIG: ${{ matrix.nginx_config }}
      run: docker compose up --build -d

    - name: Run tests
      env:
        NGINX_CONFIG: ${{ matrix.nginx_config }}
      run: ./tests/run_checks.sh

    - name: Stop services
      if: always()
      run: docker compose down
